config/routes.rb
Zthru::Application.routes.draw do
  get "attachments/create"
  resources :offers do
    collection do
      post :import
    end
  end
  resources :reviews do
    collection do
      post :import
    end
  end
  resources :attachments
  root "welcome#index"
  get "welcome/index"
  get 'get-in-dept-review' => "welcome#get_in_dept_review"
  post "send-email" => "welcome#send_email"

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :offer
  has_attached_file :file
  validates_attachment_content_type :file, :content_type => [/\Aimage\/.*\Z/,"application/pdf"]
end

app/models/email.rb
class Email < ActiveRecord::Base
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  has_many :reviews
  has_many :attachments

  extend FriendlyId
  friendly_id :title, use: :slugged

  def long_pic
    attachments.find_by_file_type("long")
  end

  def square_pic
    attachments.find_by_file_type("square")
  end

  def review
    attachments.find_by_file_type("review")
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      offer = find_by_id(row["id"]) || new
      offer.attributes = row.to_hash.slice(*offer.attribute_names)
      offer.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when ".csv" then Roo::CSV.new(file.path)
      when ".xls" then Excel.new(file.path)
      when ".xlsx" then Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :offer

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      review = find_by_id(row["id"]) || new
      review.attributes = row.to_hash.slice(*review.attribute_names)
      review.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when ".csv" then Roo::CSV.new(file.path)
      when ".xls" then Excel.new(file.path)
      when ".xlsx" then Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  def create
    @attachment = Attachment.create( attachment_params )
    redirect_to edit_offer_path(@attachment.offer)
  end

  private
    def attachment_params
      params.require(:attachment).permit!
    end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :authenticate, except: [:show, :index]
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  def import
    Offer.import(params[:file])
    redirect_to root_url
  end
  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
    @sample_offers = Offer.all.sample(5)
    @reviews = @offer.reviews

    set_meta_tags :title => @offer.title,
              :description => @offer.short_description,
              :keywords => @offer.keywords
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @offer }
      else
        format.html { render action: 'new' }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:title, :short_description, :description, :url)
    end

    def authenticate
      if params[:token] == "13752"
        session[:valid] = true
      end

      if session[:valid]

      else
        redirect_to root_path
      end
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def import
    Review.import(params[:file])
    redirect_to root_url
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @offers = Offer.limit(6)
    @reviews = Review.limit(3)
  end

  def get_in_dept_review
    @offer = Offer.find params[:offer]
  end

  def send_email
    offer = Offer.find params[:offer_id]
    email = Email.find_or_create_by_address(address: params[:email])
    ReviewMailer.send_review(email,offer).deliver
    redirect_to offer_path(offer)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/attachments/create.html.erb
<h1>Attachments#create</h1>
<p>Find me in app/views/attachments/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
   <%= display_meta_tags :site => 'ZTHRU' %>
  <link href='http://fonts.googleapis.com/css?family=Oswald:400,700,300' rel='stylesheet' type='text/css'>
</head>
<body>
  <div class="container">
    <%= render "shared/header" %>
    <%= yield %>
    <!-- <%= render "shared/footer" %> -->
  </div>
</body>
</html>

app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :short_description %><br>
    <%= f.text_area :short_description %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing offer</h1>

<%= render 'form' %>

<h2>File Management</h2>
<%= form_for @offer.attachments.new, :html => { :multipart => true } do |form| %>
  <%= form.file_field :file %>
  <%= form.select :file_type, ['long','square','review'] %>
  <%= form.hidden_field :offer_id, value: @offer.id %>
  <%= form.submit %>
<% end %>

<h2>Import Offers</h2>
<%= form_tag import_offers_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<h2>Import Reviews</h2>
<%= form_tag import_reviews_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>


<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<div id="offers" class="row">
  <div class="col-xs-12">
    <h1>LISTING OFFERS</h1>
  </div>
  <% @offers.each do |offer| %>
    <div class="col-xs-12 offer">
      <div class="image">
        <%= image_tag(offer.square_pic.file.url) if offer.square_pic.present? %>
      </div>
      <div class="text">
        <p class="title"><%= link_to offer.title, offer_path(offer) %></p class="title">
        <p class="hidden-xs"><%= offer.short_description %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/offers/new.html.erb
<h1>New offer</h1>

<%= render 'form' %>

<%= link_to 'Back', offers_path %>

app/views/offers/show.html.erb
<div id="offer" class="row">
  <div class="col-sm-9">
    <h1><%= @offer.title %></h1>
    <p><%= @offer.short_description %></p>
    <%= @offer.description.try(:html_safe) %>
    <div class="text-right action">
      <%= link_to "LEARN MORE", @offer.url, class: "btn btn-danger"%>
      <%= link_to "GET FREE IN-DEPTH REVIEW", "/get-in-dept-review?offer=#{@offer.id}", class: "btn btn-success" %>
      <p class="claim">*An in-depth review written by ZTHRU.NET, showing the exclusive details of this offer, such as the registration, process, and result.</p> 
    </div>
    <h2>WHAT PEOPLE SAY</h2>
    <div class="row">
      <% @reviews.each do |review| %>
      <% x=0 %>
      <% [0,1].sample(1) == [0] ? x = "blockquote-reverse" : x = "" %>
      <div class="col-xs-12">
        <blockquote class=<%= "#{x}" %>>
          <p><%= review.content %></p>
          <footer><%= review.username %> in <cite title="Source Title"><%= link_to review.source_name, review.source_url %></cite></footer>
        </blockquote>
      </div>
      <% end %>
      <div class="col-xs-12 text-right">
        <%= link_to 'BACK', offers_path, class:"btn btn-danger" %>
      </div>
    </div>
  </div>
  <div class="col-sm-3">
    <h3>OTHER OFFERS</h3>
    <% @sample_offers.each do |sample_offer| %>
      <p><%= link_to sample_offer.title, offer_path(sample_offer) %></p>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="row">
  <div class="col-xs-12">
    SITEMAP
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="row">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" id="brand">ZTHRU.NET</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1" style="height: 1px;">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/">HOME</a></li>
        <li><a href="/offers">OFFERS</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/welcome/_banner.html.erb
<img style="width: 100%;"class="responsive" src="http://www.banner4sale.com/wordpress/wp-content/uploads/2012/08/1Loaded-42x18-web-large.jpeg">

app/views/welcome/_offer.html.erb
<h1>
  LATEST - OFFERS
</h1>
<div class= "row">
  <% @offers.each do |offer| %>
    <div id="offer" class="col-sm-4">
      <div class="image hidden-xs">
        <%= image_tag(offer.long_pic.file.url) if offer.long_pic.present? %>
      </div>
      <div class="text">
        <p>
          <%= link_to offer.title, offer_path(offer) %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/welcome/_review.html.erb
<h2>
  LATEST - REVIEWS
</h2>
<div class="row">
  <div class="main col-sm-6">
    <div class="image">
      <img src="http://www.toastedfoot.com/wp-content/uploads/2010/09/Velvet-Bowery-Cigar-555x330.jpg">
    </div>
    <div class="text">
      <p class="title">
        welcome
      </p>
      <p>
        is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s
      </p>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="row">
      <% @reviews.each do |review|%>
        <%= render partial: "welcome/sub_highlight", locals:{review: review} %>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/_sub_highlight.html.erb
<div class="sub col-xs-12">
  <div class="image">
    <img src="http://fc06.deviantart.net/fs49/f/2009/220/b/0/Spongebob_4_150x150_PNG_by_somemilk.png">
  </div>
  <div class="text">
    <p class="title">
      <%= review.title %> | <%= link_to review.offer.title, offer_path(review.offer) %>
    </p>
    <p class="hidden-xs">is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
  </div>
</div>

app/views/welcome/get_in_dept_review.html.erb
<h1>
  Get In Dept Review on <%= @offer.title %>
</h1>
<div class="row">
  <div class="col-sm-6">
    <p>
      The review will be sent through email. Please type your email and submit then you will recive the review shortly.
    </p>
    <%= form_tag('/send-email') do %>
      <div class="form-group">
        <%= text_field_tag 'email',"", {class: "form-control", placeholder: "ENTER EMAIL", type: "email"} %>
        <%= hidden_field_tag 'offer_id',"", value: @offer.id %>
      </div>
      <%= button_tag "SUBMIT", class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<div id="highlight" class="row hidden">
  <div class="col-xs-12">
    <%= render "welcome/review" %>
  </div>
</div>
<div id="banner" class="row hidden">
  <div class="col-xs-12">
    <%= render "welcome/banner" %>
  </div>
</div>
<div id="highlight" class="row">
  <div class="col-xs-12">
    <%= render "welcome/offer" %>
  </div>
</div>